repos:
  - repo: https://github.com
    rev: v0.15.14
    hooks:
      - id: ruff
        # Bypasses breaking error crashes, allowing formatting to slide through
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        files: .*\.json
